### ISSUE TITLE
Major Bug affecting mobs, glitching out in Paper build 489 MC 1.13.2

### ISSUE THREAD

**Issue by axemwa** [PaperMC/Paper#1784]
Major Bug affecting mobs, glitching out thru blocks and chunks. They seem to be warping around sort of like endermen, using Paper build 489 MC 1.13.2 tested and confirmed
Here's a video of the issue occurring

https://www.youtube.com/watch?v=9_8QQBN8JQw&feature=youtu.be

**Comment by Spottedleaf** [comment]
confirmed for 489

**Comment by NullCase** [comment]
seconded for 489

**Comment by NullCase** [comment]
the monsters are normal in 486

**Comment by axemwa** [comment]
upto 488 they work normally

**Comment by axemwa** [comment]
Might wanna mark build 489 as unsuccessful/failed so no one else downloads it https://papermc.io/ci/job/Paper-1.13/

**Comment by RikoDEV** [comment]
I can confirm when the player puts the block they are in a different place.

**Comment by Ayymoss** [comment]
Confirmed 489 in 1.13.2...

Also, desync issues with players on client vs server positions.

**Comment by axemwa** [comment]
Yer mobs were trying to chase me but they kept going the wrong way and flipping out like endermen in the rain lol

**Comment by electronicboy** [comment]
Been looking over it but I think I'm too tired to spot it, but thanks for creating the issue;
apparently in my testing I managed to miss running into an area with mobs moving around enough to spot this (yay) I'd suggest sticking to 488 for now (This is why we don't recommend automatic updates!)

**Comment by zachbr** [comment]
I sifted through the mappings commit as well and didn't see anything, but it is touching pretty much every patch file so the signal to noise ratio is extreme.

I'll try looking at this from a different angle in the morning, 488 is still the recommended "solution" for now. Thanks for your patience.

**Comment by axemwa** [comment]
Was this fixed in this build, all systems a go? https://papermc.io/ci/job/Paper-1.13/490/

**Comment by DutchFlander** [comment]
As I see, 490 has the same issue! Also rails with minecarts are affected (extreme speed and cart moving to ground, bow not working while riding rail cart), and player position in multiplayer is also not correct (other player is running through walls, it is not at the same position checking multiplayer with 2 clients)

**Comment by axemwa** [comment]
Hmm these need to be classed as failed/unsuccessful builds with the warning icon 
![image](https://user-images.githubusercontent.com/37608633/50598344-632cbd00-0efa-11e9-99d2-3cdf9e77cba9.png)
https://papermc.io/ci/job/Paper-1.13/
added so ppl dont download it and get confused

**Comment by andrewkm** [comment]
Can confirm, players and mobs are in fact on drugs:

https://i.imgur.com/09tH8fM.png

**Comment by electronicboy** [comment]
Figured I'd better add a note here, not sure if github sends notifications etc, but fixed in build 491

**Comment by SeanWalk** [comment]
Confirmed 489 in 1.13.2

**Comment by axemwa** [comment]
I suggest marking [build 489](https://papermc.io/ci/job/Paper-1.13/489/) as a failed build so people don't download it. It's very bugged and if people download it there will be a lot more bug reports I think, just a thought

**Comment by aikar** [comment]
People shouldn't be downloading outdated versions anyways. but up to Z if he wants to remove those 2 builds.

**Comment by axemwa** [comment]
I totally agree, it was just an idea to save the hassle for u guys of having to reply to everyone who doesn't know about the bug yet, cause some people still don't know about it since it's not advertised anywhere in plain sight (that I know of) and there are some plugins that don't work in latest builds so theres always the chance of people attempting to downgrade to get their plugins to work properly and if that happens they could run into build 489 in the process. I can see that happening that's all but like u said it's upto "Z" in the end I don't mind what the result is, just a heads up. Thanx for replying

**Comment by smmmadden** [comment]
I'm kinda in the same boat as Shano, with builds after 481 I can't take b/c of some change made in Spigot that breaks Ridables.  Something about remapping the NMS that should have been done for 1.14, not 1.13.2.  So I'm behind the ball with keeping my servers current on Paper.

**Comment by zachbr** [comment]
Removing builds is tedious and annoying, we only do it for serious issues like world and data corruption and other extreme bugs, this does not qualify.

**Comment by axemwa** [comment]
So even a warning/failed build tag is out of the question? I didn't suggest to actually remove it per say I can understand why you can't and I respect that but if you do something as simple as putting this tag next to it ![image](https://user-images.githubusercontent.com/37608633/50719588-786a3d00-10ee-11e9-9cb2-9065db99c2da.png) then it should prevent people from downloading it.

It was just a suggestion anyway it's not completely neccesary I know, but thought I'd bring it up to help prevent ya from getting any duplicate issue reports on github from people who didn't know about the bug in 489. It's upto u guys wat ya wanna do in the end anyway doens't phase me personally just tryin to help ;)

**Comment by MiniDigger** [comment]
@axemwa that symbol is automatically added when the build fails. its not smth that is done manually.

**Comment by axemwa** [comment]
oh, my bad
