### ISSUE TITLE
Chunks not unloading correctly. 

### ISSUE THREAD

**Issue by mibby** [PaperMC/Paper#284]
Paper dev 733

@aikar @Zbob750 Chunks do not seem to be unloading correctly. Using normal spigot, everything seems to be fine. Did you reintroduce this issue https://github.com/PaperMC/Paper/issues/97 with either of these commits https://github.com/PaperMC/Paper/commit/74a73b72237c0c6f27b692a37e2ec39dbd850337 https://github.com/PaperMC/Paper/commit/dba25d1e86dfd546a6b4b06da7c8066d638915c1 https://github.com/PaperMC/Paper/commit/8e57fdd12b21f0945ec6564fbc73bdd4406cabc6?

Loaded chunks, entities, and tile entity count continues to rise over time.

```
[23:40:33] [Server thread/INFO]: Uptime: 6 hours 5 minutes 26 seconds
[23:40:33] [Server thread/INFO]: Current TPS = 16.61
[23:40:33] [Server thread/INFO]: Maximum memory: 28,672 MB.
[23:40:33] [Server thread/INFO]: Allocated memory: 10,240 MB.
[23:40:33] [Server thread/INFO]: Free memory: 6,518 MB.
[23:40:33] [Server thread/INFO]: World "world": 17,740 chunks, 28,124 entities, 39,693 tiles.
[23:40:33] [Server thread/INFO]: Nether "world_nether": 144 chunks, 4 entities, 2 tiles.
[23:40:33] [Server thread/INFO]: The End "world_the_end": 144 chunks, 11 entities, 381 tiles.
```

View distance of 6, only 26 players online. So there should only be ~4400 chunks loaded. (6 view distance = ~169 chunks a player) Checking the chunk areas in the timings report, there is nothing out of the ordinary that I can see in-game.

**Comment by TNTUP** [comment]
@mibby Itemframe issue is caused by Libsdisguises (I had that issue which forced me to kill 'em all) and libs fixed it and on my side it seems fixed, if you have Craftbook, try /cb reload? YOu seem to have the same issue I had before.

**Comment by aikar** [comment]
Those commits are def not an issue (1 of them doesn't even do anything)

**Comment by mibby** [comment]
@TNTUP I do not have libsdisguise installed due to the bed packet error on login. Haven't had it installed since 1.9.4's release. Tested on a local server before updating production to 1.9.4 to verify everything works. LibsDisguise didn't, thus it wasn't installed. Unless he recently fixed that error spam, I haven't had a reason to reinstall it yet. I've also already tried clearing all drops across all loaded chunks, yet the chunk view in timings is reporting high values on entities I can not find.

What would reloading craftbook accomplish? Just enumerates loaded chunks. `16814 chunk(s) for 3 world(s) processed (69ms elapsed)` And essential's GC output `World "world": 16,866 chunks, 30,042 entities, 38,690 tiles.`.

@aikar Any ideas for the leakage then? Spigot doesn't seem to have this problem from my quick testing.

**Comment by TNTUP** [comment]
@mibby idk then, sometimes when I notice bad TPS, I try this command and poof it works... but on your case I can't tell if its really CB or another plugin

**Comment by mibby** [comment]
@TNTUP Why would that even work? Makes no sense. I'm certain craftbook is not the cause of the chunk related leaks, as it isn't the first time this has happened with paper, then subsequently fixed later.

This issue doesn't seem to happen with Spigot 1.9.4, so hopefully Aikar or someone can look into it whenever they can. :( I'll be here to test if needed.

**Comment by aikar** [comment]
Lighting Queue def was a source
get latest build at temporary CI: https://ci.demonwav.com/viewLog.html?buildTypeId=Paper_Build&buildId=lastSuccessful&tab=artifacts

**Comment by mibby** [comment]
@aikar I think there is an edge case issue still with chunk unloading. Entity count continues to rise the longer the server has been up. And tps starts taking a dive, as well as save-all performance starts lagspiking / delayed a second or two rather than instant.

https://timings.aikar.co/v2/?id=deb482d38d164bc095b8285737d7596b
https://timings.aikar.co/v2/?id=e6ee42a8e273439591762cfc55bb427d

**Comment by pola** [comment]
I can confirm it's an issue in 740, but only when `queue-light-updates` is set to `true`. If I change the value of queue-light-updates to false, the chunks seem to start unloading like they should.

Here's some performance data from when `queue-light-updates` was set to `true` (notice the `chunks` column):
`time,players,entities,chunks,tiles,memory,tps
1463225701,53,39982,12554,181906,10737418240,13.16
1463226001,50,39424,12760,181677,10737418240,13.32
1463226302,50,39387,13685,183050,10737418240,12.85
1463226600,57,38734,14905,178827,10737418240,13.14
1463226901,55,38499,17057,180367,10737418240,12.5
1463227200,57,37677,18213,180077,10737418240,12.32
1463227501,59,36918,19306,182110,10737418240,12.38
1463227800,55,37238,21493,181128,10737418240,12.08
1463228101,57,36897,23609,177978,10737418240,11.63
1463228400,58,37629,25071,180138,10737418240,11.54
1463228701,60,37034,26249,177808,10737418240,10.7
1463229000,62,37431,28084,182929,10737418240,9.51
1463229301,62,38527,29357,188134,10737418240,8.77
1463229601,62,39362,30446,183634,10737418240,8.77
1463229902,59,39006,31781,183896,10737418240,8.58
1463230200,60,39415,32952,186331,10737418240,8.26
1463230501,54,40000,34550,188545,10737418240,6.95`

...and here's some more perfdata from when `queue-light-updates` was set to `false`:
`time,players,entities,chunks,tiles,memory,tps
1463256395,30,35346,7893,174826,10481565696,19.29
1463256600,31,34359,7976,171469,10514595840,20.0
1463256901,34,34177,8364,169340,10544480256,17.28
1463257200,34,33185,8001,161777,10563354624,20.0
1463257501,32,31956,7642,156278,10589569024,19.9
1463257800,34,31451,7951,153698,10560733184,20.0
1463258101,37,30728,8323,151690,10554966016,19.92
1463258400,39,29854,7834,147165,10549723136,19.81`

**Comment by TNTUP** [comment]
I have queue-light-updates to true, should I disable it? I'm still on Paper #727, wont update to 1.9.4 due to plugins and I'm still using Forge 1.9's :/

**Comment by mibby** [comment]
@aikar On paper 740, queue lighting enabled.

Chunk count and entities continue to rise the longer the server has been up.

https://timings.aikar.co/v2/?id=76873cc23e19438d81dd91dca6654ab4
https://timings.aikar.co/v2/?id=ced2e2dde36a445ca5880daed90d0a6e

Also noticed that the chunk count number is significantly smaller than what the in-game report with GC is. For example ```/gc``` output right now is 6,783 chunks in 'world' while the timings report states 120.

**Comment by ghost** [comment]
Same issue as mibby here, build 740. Absolutely no plugins or settings changed from 1.9.2 to 1.9.4. Server was up for 120 hours once on last 1.9.2 paper build with no issues, entities didn't keep rising forever and ChunkUnload did not look this bad!

![gdssd](https://cloud.githubusercontent.com/assets/18597710/15271677/d2b93582-1a55-11e6-8d99-36ae37f071cc.png)

Testing now if it's the light queue setting causing it

Yeah seems to be the light queue option, setting it to false fixes it. No absurd amount of entities or big ChunkUnload usage and server is 20 tps stable after 13 hours

**Comment by aikar** [comment]
Please try Paper 743, should resolve this.

**Comment by mibby** [comment]
@aikar On paper 749, queue lighting enabled.

https://timings.aikar.co/v2/?id=a50f99b76f7d42beb65a1754496dfa63
https://timings.aikar.co/v2/?id=46b9cf3484bf40449bd6453b647f9cb8
https://timings.aikar.co/v2/?id=70ee080098354d00a7e33a8c3c2aa3b0

The count count on the graph still continues to rise. And the tile entity count on the graph is incorrect.

```
[20:42:40] [Server thread/INFO]: Uptime: 4 hours 42 minutes 27 seconds
[20:42:40] [Server thread/INFO]: Current TPS = 19.92
[20:42:40] [Server thread/INFO]: Maximum memory: 28,672 MB.
[20:42:40] [Server thread/INFO]: Allocated memory: 10,240 MB.
[20:42:40] [Server thread/INFO]: Free memory: 4,653 MB.
[20:42:40] [Server thread/INFO]: World "world": 5,599 chunks, 6,907 entities, 12,980 tiles.
[20:42:40] [Server thread/INFO]: Nether "world_nether": 144 chunks, 3 entities, 2 tiles.
[20:42:40] [Server thread/INFO]: The End "world_the_end": 144 chunks, 4 entities, 382 tiles.
```

**Comment by Brokkonaut** [comment]
For our server this bug is fixed now, all chunks are unloading again :)

**Comment by Postremus** [comment]
yup, chunks are unloading for use, too, on b394ec047236138350857b347cee8a07203c72a6.
https://timings.aikar.co/v2/?id=6d6474d9179c42cb8ce9bde9fef9999c constant, even though i forced loading of the chunks in a 2000x2000 block area.

**Comment by zachbr** [comment]
Closing as resolved
