### ISSUE TITLE
Block Update Bug

### ISSUE THREAD

**Issue by Plutoren** [PaperMC/Paper#3145]
### What behaviour is expected:
Blocks would not randomly change after being world edited.

### What behaviour is observed:
When you have a tickable block, meaning one that is randomly ticked to check for updates such as growth like say grass, or ice, farmland, plants, etc and then you world edit that block to something else such as say stone, the block continues to tick as if it were the previous block. See the video below.  

### Steps/models to reproduce:
Place something like ice, farmland, bamboo, etc and then world edit away then wait a few seconds for those blocks to randomly update and then you will see the issue. 
Here's a nice video for you https://youtu.be/ydeKxNrnxv4

### Plugin list:
![159a81d90c3327d23cedda6c1a23522c](https://user-images.githubusercontent.com/6248819/79291054-a1ee4880-7e9b-11ea-963d-ec2067547c48.png)
I can test it again without plugins but I highly doubt any of my plugins are causing this.

### Paper build number:
![083e327d2dcb0fda6f87b3b68b339a0d](https://user-images.githubusercontent.com/6248819/79290751-e9c0a000-7e9a-11ea-8825-83163f6c59de.png)
I didn't test it on a plugin free server but I feel that it is highly unlikely that a plugin has anything to do with this, especially since the bug is relatively new. 

### Anything else:
I believe this pull is what made the bug possible https://github.com/PaperMC/Paper/pull/2914

**Comment by chickeneer** [comment]
It appears that you are running build #156. Please update - Paper is on build #183 now.

Additionally, I was not able to replicate this with regular WorldEdit. I suspect either caused by an outdated build. or FAWE....

**Comment by Plutoren** [comment]
I just ran it on a test server with the latest build as well as FAWE. Seen here https://youtu.be/WObs7T4x3jc The issue does persist. I also tested it with normal world edit and the bug was fixed. It would seem the way FAWE updates blocks is different, probably explains why it is faster. I'm not sure if this is something you guys want to address or if FAWE would need to change its methods. Let me know and I can report it to them instead.

**Comment by chickeneer** [comment]
It would be best to report to FAWE. They do things that are not through the Bukkit/Paper API.

**Comment by dordsor21** [comment]
**What behaviour is expected:**
After ticking blocks (tested: saplings, dirt) are removed (setting to glass, air, etc) they will not continue to tick.

**What behaviour is observed:**
After ticking blocks (tested: saplings, dirt) are removed (setting to glass, air, etc) the server continues to tick the blocks, therefore setting the blockstate at the locations they were removed from to the ticked state. This means that chunks are not being correctly read during the ticking process.

**Steps/models to reproduce:**
Set an area to glass and saplings (example) with //set 99%glass,1%oak_sapling
Restart server (the saplings that are placed are not ticked until a restart)
Set the area to glass
Increase randomtickspeed (to have it occur faster, 300 works well)
Enjoy as all the sapling come back from the dead

**Plugin list:**
FastAsyncWorldEdit, PlotSquared, Vault, (WorldEdit - FAWE), zPermissions

**Paper build number:**
185

**Anything else:**
I know y'all hate the way FAWE handles block setting, but it works on Spigot. Paper's method of block ticking may well cause issues in other cases, as the blocks are written directly to the chunk.

The following is where the changes are written to the chunk
https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/1.15/worldedit-bukkit/src/main/java/com/boydti/fawe/bukkit/adapter/mc1_15_2/BukkitGetBlocks_1_15_2.java#L271

**Comment by dordsor21** [comment]
It's actually even worse than that. Running recalcBlockCounts on all chunk sections does not fix the issue.

I'm 95% sure that the blocks are actually correctly removed from the tickinglist in the chunk, but the server still ticks the blocks anyway (using debug in the recalcBlockCounts showed it was removing then adding different numbers of locations from the chunk's ticking list before and after setting all saplings to glass). This is pretty serious if these tickingblocks are somehow being found again.

**Comment by aikar** [comment]
Bug would be in this patch: 
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0446-Optimise-TickListServer-by-rewriting-it.patch

would appreciate any suggestions on what the issue may be.

**Comment by aikar** [comment]
I've added a config to turn this patch off,

under settings in paper.yml

```
settings:
  use-optimized-ticklist: false
```

I'm not default adding it there as I hope this is temporary. Please let me know if this fixes the issue.

I've also had many spurious reports about random ghost blocks just from redstone usage, not even with FAWE, so the concern is valid and im trying with it off on my own server too.

Hopefully leaf can identify what the issue is if it is in this patch.

**Comment by Spottedleaf** [comment]
yes it's known to me that random ticking (not the ticklist - you hit the wrong area, ticklist has consistency checks before executing a tick) will cause this exact behaviour if plugins don't use chunksection#setType
newest random ticking method should be better, as setType/recalculate blocks will now work even if the chunk section has no attached chunk

tick methods for ticklist:
```
    private void a(NextTickListEntry<FluidType> nextticklistentry) {
        Fluid fluid = this.getFluid(nextticklistentry.a);

        if (fluid.getType() == nextticklistentry.b()) {
            fluid.a((World) this, nextticklistentry.a);
        }

    }

    private void b(NextTickListEntry<Block> nextticklistentry) {
        IBlockData iblockdata = this.getType(nextticklistentry.a);

        if (iblockdata.getBlock() == nextticklistentry.b()) {
            iblockdata.a(this, nextticklistentry.a, this.random);
        }

    }
```

**Comment by dordsor21** [comment]
This seems to be fixed now, thanks guys.

**Comment by aikar** [comment]
@dordsor21 is that fixed WITH optimized ticklist or without?

I want to remove that config soon as we are confident it is not the source.

**Comment by aurorasmiles** [comment]
Apparently it is fixed without changing/disabling that option, at least as far as we could test it

**Comment by dordsor21** [comment]
Yeah from what I could test it's fixed _**with**_ the optimized ticklist. Unsure if there are any fringe cases, but since the config option is ghosted anyway it might be worth keeping for a while so any similar issues can be debugged easier.

**Comment by Plutoren** [comment]
So I ran some tests with the latest everything on a dev server with only FAWE-180 and Paper-220.

Basically I found that when you run a world edit command it halts all block updates in the entire chunk of the edit. This technically does prevent the original bug since it will no longer update the world edited blocks into anything weird. But it does present a new bug where nothing that should be updated continues to be updated.

Video: https://youtu.be/sIwJOSDcGx8

**Comment by TheoRetisch1** [comment]
Is there any news on a possible fix yet? Do you need more information? Or is it just quite complex and annoying to debug the shit?

**Comment by aikar** [comment]
can anyone reproduce without FAWe? if so, how?

I tested with normal WE and it seems to work fine.

FAWE needs to figure that out.

**Comment by dordsor21** [comment]
I know what the issue is in FAWE. It's just something to be gotten round to. That's not related to this issue though, and should be raised on the FAWE github if there's not already an issue.

**Comment by TheoRetisch1** [comment]
I did a quick test. The only problem I have is that blocks like farmland do not update correctly (very slowly irregularly). But this happens even without worldedit actions. I can't reproduce the bug described above with FAWE, nor with Worldedit.
I do not have bug #3251. Since I don't have the bugs it makes no sense to specify the test environment. It was just a quick test.
I still have the bug regarding clone commands in command chains, which I reported in #3247, one to one as described. I can also reproduce it with normal worldedit and without worldedit (actually worldedit is not even used) and provide more information if necessary. But this is already in the ticket. We have a pretty wild mix of bugs here, are you sure they are all connected?

**Comment by chickeneer** [comment]
This issue should be able to be closed. FAWE reportedly fixed the issue on their latest build.
https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/0ca81e9d67be72cdb4b7176b2a83ab60f6c529f2

**Comment by dordsor21** [comment]
> This issue should be able to be closed. FAWE reportedly fixed the issue on their latest build.
> [IntellectualSites/FastAsyncWorldEdit@0ca81e9](https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/0ca81e9d67be72cdb4b7176b2a83ab60f6c529f2)

I mean, the original issue was fixed by paper over a week ago. This seemed to become an entirely different issue (which was fixed above).

**Comment by aikar** [comment]
@dordsor21 no there was still pending issue with FAWE.
https://github.com/PaperMC/Paper/issues/3145#issuecomment-619699767

**Comment by dordsor21** [comment]
I figured since it wasn't within the scope of the original issue (and wasn't actually a paper issue - same occurred in spigot) this could be closed regardless. But even so, that's now been fixed in FAWE anyway.

**Comment by aikar** [comment]
I had originally left this open incase there was a paper issue, but i think there was separate issues and going to close this in favor of https://github.com/PaperMC/Paper/issues/3251 for tracking any paper side issues.
