### ISSUE TITLE
Certain blocks in certain positions stay in the same state forever

### ISSUE THREAD

**Issue by Ryoyo2** [PaperMC/Paper#3251]
### What behaviour is expected:
Redstone lanterns go out when not having a signal, water without source blocks disappears, redstone trails/repeaters carry their signal as intended, observers work as intended.

### What behaviour is observed:
In certain locations, certain blocks basically just stop updating and continue to be in the same state, despite turning signals on or off or breaking the block and re-placing it.  To illustrate the issue, I'll give you multiple examples. 

![contraption](https://i.imgur.com/uUDVryr.png)

In this contraption, dispensers will drop water onto the observers below, turning redstone lamps underneath it on or off. You can already see the floating water there, which doesn't have a source block but will still linger there unless manually removed with blocks. This issue will repeat every time the dispensers are turned back on and water gets released and taken back in the dispenser.

![lamp](https://i.imgur.com/jw6lmV8.png)

In certain areas, once the redstone lamp is on, there is no way to turn it off again by removing the signal, only by destroying it and replacing it, but as soon as the redstone lamp will get a signal again for a second, it will stay on forever until I repeat the process.

![lamps](https://i.imgur.com/V78sEC4.png)
These lamps will stay on forever even without a signal until destroyed and replaced and if provided with a signal again, will continue to stay on forever. - The issue also seems to be gradually spreading further as it is now more than 20 lamps and observers with this broken behavior. In some cases the lamps are stuck in their state, in other cases the observers are stuck in their state.

![repeater](https://i.imgur.com/L9ug78F.png)
Same thing happens with repeaters and redstone trails, they will either stay on forever or not carry a signal anymore, everything breaks down after a while and gets stuck in a permanent state of being either on or off it seems.

Interestingly enough, these issues only occur with certain blocks in certain positions - although it seems to spread over time. If I were to move the entire contraption one block higher, it would work fine. The first time these things occured, we rerouted some of the redstone and it worked fine but after some time, things broke again. In some cases, it will also work to simply replace the block that was there before with a different one, at least in circuits e.g. replace a redstone trail with repeaters - But those also broke again after a while.

### Steps/models to reproduce:
I wish I knew. This issue came out of the blue and is now spreading around what it seems the entire area - hopefully not the entire server though.

### Plugin list:
https://timings.aikar.co/?id=29a379915a0f4899bc8cb6b2593570cd

### Paper build number:
Paper #266

### Anything else:

I have use-faster-eigencraft-redstone: true - in case that is relevant, although it seems to affect more than just redstone.

Things I have tried to fix the issue:
- relogging
- restarting server
- updating paper to latest (from #220 to #226)
- destroying everything around it and the blocks themselves and re-placing everything, basically every measure that would update a block-state
- changing states of redstone lamp with debug stick - which does turn them off, but as soon as they get even a milisecond signal again, they will stay on permanently again.
- using worldedit //regen on an area
- tried with both use-optimized-ticklist: true - as well as false
- copying region file to a different server that doesn't run any plugins - same issue occurs there

I've included the region file for you to download to see for yourselves:
https://drive.google.com/file/d/1aUjE72A7DvkYMRHPGustIZb1vfwbrbTO/view?usp=sharing

The teleport coordinates are:
X: 1924
Y: 18
Z: 54

**Comment by Trigary** [comment]
Can this issue be reproduced without plugins or on vanilla?

**Comment by Ryoyo2** [comment]
As described (in my arguably very long post) above, I was able to reproduce the issue on the newest version of paper (226), running no plugins. I'd have to do testing with vanilla though.

**Comment by Trigary** [comment]
Sorry about that, I didn't read the "anything else" section.

**Comment by Trigary** [comment]
Which was a terrible error on my part... Since you have already tested without plugins, can you please test without eigencraft-redstone as well? It might be the issue (I sincerely hope it isn't, since having to fix that won't be fun to say the least).

**Comment by Ryoyo2** [comment]
No worries! I'll gladly assist to the best of my ability in answering any questions or doing testing as this has been grinding me and my players gears for days now. I'll test it right now without eigencraft and will report back immediately. You may also contact me on discord under Ryoyo#9882 if that helps communication-wise. I will keep this thread updated in any case should there be any new insights or testing done.

**Comment by Ryoyo2** [comment]
I can confirm that the issue persists after switching off eigen-redstone. No change. The reason why I suspect that this is not only to do with redstone but block-states in general is the issue with water not disappearing or flowing when it is supposed to either. If you'd like me to do any additional testing, you can let me know any time.

**Comment by Ryoyo2** [comment]
It seems however that the same issues re-occur in a singleplayer world with that region file. Not sure if that's a vanilla bug or if there's somehow issues in only certain parts of these chunks or if the chunks are slowly corrupting since the issue keeps spreading? I'm very confused. I did run regionfixer to see if something was wrong with the chunks but there seems to be no issues.

**Comment by aikar** [comment]
This is same issue as https://github.com/PaperMC/Paper/issues/3145
Please follow that issue, potential fix coming

**Comment by aikar** [comment]
Reopening for the water portion, but as discussed on discord, redstone seems maybe typical vanilla behavior of redstone randomly getting stuck.

but the water issue is something to look into.

**Comment by Ryoyo2** [comment]
Not wanting to disrespect but to me personally, it seems like all of the issues described are the same and I highly doubt it is typical vanilla behavior that all of this circuitry or water just breaks and becomes unfixably stuck in certain states within short time frames - I strongly believe this issue would be more common if that was the case. It's just a suggestion but I don't think that focusing on redstone helps here as this seems to be more part of a larger issue.

The way that I see it, there are certain locations, in which certain blocks e.g. water/redstone just become stuck in a state once activated or deactivated. I don't believe that this is limited to water or redstone either but I have no real way of testing it since the behavior of things breaking is fairly random.

Take the redstone lamp as an example: It is on permanently - If I destroy it and re-place it and give it a signal, it becomes stuck again in the state of being on. Same thing with the water. I can remove it but once I add it again, it will behave exactly as before. It is as if the location itself saves the state of a certain block only and never resets it, even after destroying the block. Once it gets back to the state it became stuck in in the first place with the same block from before, it will stay that way forever.

And seeing as this issue is spreading around in this general area, I can't help but think that both the redstone getting stuck, as well as the water getting stuck are exactly the same issue, these blocks are next to each other after all and are all behaving exactly in the same manners.

**Comment by Ryoyo2** [comment]
I have an update on this. While I keep seeing the same issue pop up a lot recently in the paper-help channel, it fixed itself in the affected area on my server. I did not restart the server, nor update paper. In fact, I made no changes whatsoever to anything. It just suddenly worked as intended after leaving the area alone for a while and coming back to it, although I doubt the overarching issue is fixed. I will keep observing the area to see if the issue comes back.

**Comment by Wirlie** [comment]
Hello! I do not know if my issue is related to this, but since last weeks some players of my server have reported that the redstone gets stuck after some time and I do not know how I can fix this.

I have tried disabling `eigencraft-redstone` but the issue still happens.

This have started happening since I have updated to recent version of Paper.
My version: `This server is running Paper version git-Paper-284 (MC: 1.15.2)`

Plugin list:
https://gist.github.com/Wirlie/429d3ff0856866ba179057e0cc0c9427

![2020-05-16_11 48 55](https://user-images.githubusercontent.com/7508197/82125413-6cbf6980-976b-11ea-85c3-69635f0ee49f.png)

I have tried replacing the affected repeaters (breaking and placing it), but repeater seems to not react to the new redstone signal and remains off.

![2020-05-16_11 49 14](https://user-images.githubusercontent.com/7508197/82125452-a2645280-976b-11ea-9b63-c7f7f8c17adf.png)

If I move the mechanism one block up then all starts working again:

![2020-05-16_12 11 37](https://user-images.githubusercontent.com/7508197/82125857-6a124380-976e-11ea-9540-6701128f4471.png)

Players have reported that this also happens to other redstone blocks such dispensers, droppers, observers, comparators.

**Comment by Ryoyo2** [comment]
Yep, that is definitely the same issue. We also had redstone that was permanently off, not just on.

**Comment by Spottedleaf** [comment]
The regionfile you have shows that the stuck blocks already have a tick scheduled for them. One of the repeaters is scheduled to tick in 1176825032 ticks, which is about 2 years. Exact same thing for the water.

Please set the flag `-Dpaper.ticklist-warn-on-excessive-delay=true` and I will add logic to the scheduler to detect when world time is not as expected, and add a flag to cleanup existing issues.

**Comment by Ryoyo2** [comment]
Wow, thanks Leaf! Haven't had this issue on my mind in quite a while (although it has popped up once in a while on the server) - but I'm super happy to see it's still being looked at. Much appreciated!

**Comment by Jsimpki** [comment]
Issue is reoccuring within 1.18.1 servers

**Comment by Machine-Maker** [comment]
Please open a new issue with the latest 1.18.2 version of paper describing your issue.
