### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by ToasterBathMaster** [PaperMC/Paper#3319]
For a while now, I have been running a server on Minehut (IP: hamwtoast.minehut.gg) and have had no issues whatsoever. However, my staff recently reported an insane number of zombie pigmen close to where his house is (screenshot from them below)

![image](https://user-images.githubusercontent.com/65004763/81379436-b391db80-913b-11ea-92b3-8f5c5364c9d9.png)

This is what I suspect to be causing the server to crash and I have sent out emails to MH and posted in the forums, but nobody has been able to help me. 

Every time a player logs onto the server, it will take the server about 10 seconds to post a lot of code into the console before kicking the player and shutting down the server. 

I can still start the server from the dashboard at minehut.com, but when I log on, I can't execute any commands (/butcher or /killall to fix the issue) nor move to load any chunks. I have tried executing commands from the console to kill the zombie pigmen, and though it says it has been sent and the pigmen have been killed, the lag still persists.

Whenever I go on the server to fix it, I get kicked and disconnected. The game will refuse to load any new chunks, and trying to load new chunks will crash the server. 

Doing `/tps` into the server console through the MH dashboard reports tps of 20,20,20. While that is meant to be the best, most lag free TPS possible, everyone that tries to join gets kicked and is sent a message saying that the "server you were on previously has crashed, and you have been sent to a fallback server."

For awhile, this has been going on, and when I look into the console, it always says DO NOT REPORT THIS TO PAPER, THIS IS NOT A BUG OR A CRASH. However, recently, I have gotten this message, which has forced me to come here for help.

This message shows up with the DiscordSRV plugin every time the server crashes, and I don't know what it means.
![Screen Shot 2020-05-08 at 15 01 44](https://user-images.githubusercontent.com/65004763/81380114-de306400-913c-11ea-99d1-38e04edd4729.png)

Below is the console error message.
[Fri, 8. May 2020 05:04:40 GMT ERROR] The server has stopped responding! This is (probably) not a Paper bug.
[Fri, 8. May 2020 05:04:40 GMT ERROR] If you see a plugin in the Server thread dump below, then please report it to that author
[Fri, 8. May 2020 05:04:40 GMT ERROR]      *Especially* if it looks like HTTP or MySQL operations are occurring
[Fri, 8. May 2020 05:04:40 GMT ERROR] If you see a world save or edit, then it means you did far more than your server can handle at once
[Fri, 8. May 2020 05:04:40 GMT ERROR]      If this is the case, consider increasing timeout-time in spigot.yml but note that this will replace the crash with LARGE lag spikes
[Fri, 8. May 2020 05:04:40 GMT ERROR] If you are unsure or still think this is a Paper bug, please report this to https://github.com/PaperMC/Paper/issues
[Fri, 8. May 2020 05:04:40 GMT ERROR] Be sure to include ALL relevant console errors and Minecraft crash reports
[Fri, 8. May 2020 05:04:40 GMT ERROR] Paper version: git-Paper-224 (MC: 1.15.2)
[Fri, 8. May 2020 05:04:40 GMT ERROR] ------------------------------
[Fri, 8. May 2020 05:04:40 GMT ERROR] Server thread dump (Look for plugins here before reporting to Paper!):
[Fri, 8. May 2020 05:04:40 GMT ERROR] ------------------------------
[Fri, 8. May 2020 05:04:40 GMT ERROR] Current Thread: Server thread
[Fri, 8. May 2020 05:04:40 GMT ERROR]     PID: 16 | Suspended: false | Native: false | State: RUNNABLE
[Fri, 8. May 2020 05:04:40 GMT ERROR]     Stack:
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.RegistryBlockID.fromId(RegistryBlockID.java:53)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.DataPaletteGlobal.a(SourceFile:29)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.DataPalette.getObject(DataPalette.java:12)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         com.destroystokyo.paper.util.maplist.IBlockDataList.getBlockDataFromRaw(IBlockDataList.java:33)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.WorldServer.a(WorldServer.java:672)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.ChunkProviderServer.lambda$tickChunks$12(ChunkProviderServer.java:860)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.ChunkProviderServer$$Lambda$3542/612831990.accept(Unknown Source)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:287)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:779)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:715)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:435)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1303)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.lang.Thread.run(Thread.java:748)
[Fri, 8. May 2020 05:04:40 GMT ERROR] ------------------------------
[Fri, 8. May 2020 05:04:40 GMT ERROR] Entire Thread Dump:
[Fri, 8. May 2020 05:04:40 GMT ERROR] ------------------------------
[Fri, 8. May 2020 05:04:40 GMT ERROR] Current Thread: OkHttp Dispatcher
[Fri, 8. May 2020 05:04:40 GMT ERROR]     PID: 114 | Suspended: false | Native: false | State: TIMED_WAITING
[Fri, 8. May 2020 05:04:40 GMT ERROR]     Stack:
[Fri, 8. May 2020 05:04:40 GMT ERROR]         sun.misc.Unsafe.park(Native Method)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.lang.Thread.run(Thread.java:748)
[Fri, 8. May 2020 05:04:40 GMT ERROR] ------------------------------
[Fri, 8. May 2020 05:04:40 GMT ERROR] Current Thread: ForkJoinPool-2-worker-11
[Fri, 8. May 2020 05:04:40 GMT ERROR]     PID: 104 | Suspended: false | Native: false | State: TIMED_WAITING
[Fri, 8. May 2020 05:04:40 GMT ERROR]     Stack:
[Fri, 8. May 2020 05:04:40 GMT ERROR]         sun.misc.Unsafe.park(Native Method)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[Fri, 8. May 2020 05:04:40 GMT ERROR] ------------------------------
[Fri, 8. May 2020 05:04:40 GMT ERROR] Current Thread: JDA RateLimit-Worker 5
[Fri, 8. May 2020 05:04:40 GMT ERROR]     PID: 100 | Suspended: false | Native: false | State: WAITING
[Fri, 8. May 2020 05:04:40 GMT ERROR]     Stack:
[Fri, 8. May 2020 05:04:40 GMT ERROR]         sun.misc.Unsafe.park(Native Method)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.lang.Thread.run(Thread.java:748)
[Fri, 8. May 2020 05:04:40 GMT ERROR] ------------------------------
[Fri, 8. May 2020 05:04:40 GMT ERROR] Current Thread: JDA RateLimit-Worker 4
[Fri, 8. May 2020 05:04:40 GMT ERROR]     PID: 99 | Suspended: false | Native: false | State: WAITING
[Fri, 8. May 2020 05:04:40 GMT ERROR]     Stack:
[Fri, 8. May 2020 05:04:40 GMT ERROR]         sun.misc.Unsafe.park(Native Method)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.lang.Thread.run(Thread.java:748)
[Fri, 8. May 2020 05:04:40 GMT ERROR] ------------------------------
[Fri, 8. May 2020 05:04:40 GMT ERROR] Current Thread: DiscordSRV - Channel Topic Updater
[Fri, 8. May 2020 05:04:40 GMT ERROR]     PID: 98 | Suspended: false | Native: false | State: TIMED_WAITING
[Fri, 8. May 2020 05:04:40 GMT ERROR]     Stack:
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.lang.Thread.sleep(Native Method)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         github.scarsz.discordsrv.objects.threads.ChannelTopicUpdater.run(ChannelTopicUpdater.java:55)
[Fri, 8. May 2020 05:04:40 GMT ERROR] ------------------------------
[Fri, 8. May 2020 05:04:40 GMT ERROR] Current Thread: JDA RateLimit-Worker 3
[Fri, 8. May 2020 05:04:40 GMT ERROR]     PID: 96 | Suspended: false | Native: false | State: WAITING
[Fri, 8. May 2020 05:04:40 GMT ERROR]     Stack:
[Fri, 8. May 2020 05:04:40 GMT ERROR]         sun.misc.Unsafe.park(Native Method)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.lang.Thread.run(Thread.java:748)
[Fri, 8. May 2020 05:04:40 GMT ERROR] ------------------------------
[Fri, 8. May 2020 05:04:40 GMT ERROR] Current Thread: DiscordSRV - Console Message Queue Worker
[Fri, 8. May 2020 05:04:40 GMT ERROR]     PID: 95 | Suspended: false | Native: false | State: TIMED_WAITING
[Fri, 8. May 2020 05:04:40 GMT ERROR]     Stack:
[Fri, 8. May 2020 05:04:40 GMT ERROR]         java.lang.Thread.sleep(Native Method)
[Fri, 8. May 2020 05:04:40 GMT ERROR]         github.scarsz.discordsrv.objects.threads.ConsoleMessageQueueWorker.run(ConsoleMessageQueueWorker.java:62)
[Fri, 8. May 2020 05:04:40 GMT ERROR] ------------------------------
[Fri, 8. May 2020 05:04:40 GMT ERROR] Current Thread: DiscordSRV - Presence Updater

**Here are all the plugins in my server:**
![Screen Shot 2020-05-08 at 15 06 36](https://user-images.githubusercontent.com/65004763/81380453-88a88700-913d-11ea-8e0d-8e754a95ed5e.png)

I have no known way to reproduce this action, and I don't even know who did it.

When I do `/version` through console, the console returns:
[Fri, 8. May 2020 07:09:34 GMT INFO] This server is running Paper version git-Paper-224 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[Fri, 8. May 2020 07:09:34 GMT INFO] Previous version: git-Paper-155 (MC: 1.15.2)
[Fri, 8. May 2020 07:09:34 GMT INFO] You are 37 version(s) behind

P.S. My server RAM is 1024 MB, as per MH's free server plan, and I plan to upgrade very soon. According to the error message shown above, is this a problem with RAM?

I have been working on this server for an unholy amount of time and my Discord is ɹǝʇsɐɯɥʇɐqɹǝʇsɐoʇ#8888, so please GM me there if you have any support. Any help will be very greatly appreciated.

Many Thanks, M

**Comment by ToasterBathMaster** [comment]
PPS. One of my server staff has killed all of the pigmen in both the nether and overworld and reports that the nether is completely lag-free. All commands work in the nether, but the server still freaks out in the overworld.

**Comment by ntoonio** [comment]
If I'm understanding your issue correctly, I guess the commands are only killing the pigmen in the chunks that are currently loaded. Maybe you can try to download the world and join it in singleplayer, kill the pigmen, and then upload it again

**Comment by guinhill** [comment]
I can report I have had similar issues on my server, 
They did not occur anymore when I disabled a few plugins, DiscordSRV being one of them.
I have yet to enable these plugin's again. Since they were nice to have for me.


__
Would setting /dificulty peacefull 
just before you fly in to the area work. 
Should force the pigmen to despawn.

**Comment by ShaneBeee** [comment]
> [Fri, 8. May 2020 07:09:34 GMT INFO] This server is running Paper version git-Paper-224 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[Fri, 8. May 2020 07:09:34 GMT INFO] Previous version: git-Paper-155 (MC: 1.15.2)
[Fri, 8. May 2020 07:09:34 GMT INFO] You are 37 version(s) behind

37 versions behind? Don't you think it would be a good idea to update your Paper version before reporting a bug?
37 updates.... might have been fixed!

**Comment by ToasterBathMaster** [comment]
> If I'm understanding your issue correctly, I guess the commands are only killing the pigmen in the chunks that are currently loaded. Maybe you can try to download the world and join it in singleplayer, kill the pigmen, and then upload it again

Sorry, but I must have forgot to mention, but the server doesn't allow me to download the world, as I can't do any commands.

**Comment by ToasterBathMaster** [comment]
> I can report I have had similar issues on my server,
> They did not occur anymore when I disabled a few plugins, DiscordSRV being one of them.
> I have yet to enable these plugin's again. Since they were nice to have for me.
> 
> __
> Would setting /dificulty peacefull
> just before you fly in to the area work.
> Should force the pigmen to despawn.

Could I have some clarification on what other plugins you disabled?

Update: I disabled every one of the plugins I had active on the server and the crashing still persists. Is this a RAM issue?

**Comment by FabioZumbi12** [comment]
I am having a similar issue here, but with the latest version (280)! Here's my timings:

https://timings.aikar.co/?id=b3bb1dd90a4f4b78885916d5939662a8

Running for only +- 10m

This seems to be interesting to analyse:
![image](https://user-images.githubusercontent.com/5833818/81767615-3b1a7a00-94af-11ea-878d-2e82ab7664d3.png)

After this lag, the RAM blows up until crash

**Comment by FabioZumbi12** [comment]
I had a similar issue (and posted here... and then deleted after solve the problem).

In my problem, the issue is my HDs. One of my HDs, for some reason, got inaccessible, causing read and write issues with my other all HDs making all work too low.

It seems when the server cant write the chunk on time, that chunks go all to memory, and more... and  end crashing the server.

Try to checking this!
