### ISSUE TITLE
Itemframes sometimes fail to spawn in Paper-268 and above.

### ISSUE THREAD

**Issue by Symphonic3** [PaperMC/Paper#3368]
### What behaviour is expected:
An item frame spawns.

### What behaviour is observed:
An IllegalArgumentException is thrown

### Steps/models to reproduce:
Create a script that spawns lots of itemframes in valid positions, and it will sometimes randomly fail.

### Plugin list:
N/A, this is caused by my plugin spawning entities, but the bug is in paper itself because when reverting to older builds it no longer occurs.

### Paper build number:
Paper-268

**Comment by zachbr** [comment]
Can we see the stacktrace from the IllegalArgumentException?

**Comment by Symphonic3** [comment]
```
>.... [14:43:34 WARN]: [SCP] Task #93 for SCP v0.1 generated an exception
java.lang.IllegalArgumentException: Cannot spawn hanging entity for org.bukkit.entity.ItemFrame at Location{world=CraftWorld{name=main},x=-40.0,y=35.0,z=-49.0,pitch=0.0,yaw=0.0}
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.createEntity(CraftWorld.java:1910) ~[patched_1.15.2.jar:git-Paper-268]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1955) ~[patched_1.15.2.jar:git-Paper-268]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1541) ~[patched_1.15.2.jar:git-Paper-268]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawnEntity(CraftWorld.java:767) ~[patched_1.15.2.jar:git-Paper-268]
at net.scpuncontained.SCP.doors.NormalDoor$3.run(NormalDoor.java:164) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-268]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-268]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1252) ~[patched_1.15.2.jar:git-Paper-268]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-268]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1169) ~[patched_1.15.2.jar:git-Paper-268]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Paper-268]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by zachbr** [comment]
Can you reproduce on latest (282) and send us an updated stacktrace if so?
There were some changes to collisions that could be causing this and they should be fixed now, but your build (268) was still affected.

**Comment by Symphonic3** [comment]
It was on 282 when I noticed the issue in the first place, I will reproduce and send the stacktrace

**Comment by aikar** [comment]
In this specific case im not sure it would be fixed, but I guess we can make an improvement here.

The root issue is that its spawning right on the edge of an unloaded chunk.

**Comment by Symphonic3** [comment]
Interesting @aikar , I never thought to check chunk borders.

Here is the stacktrace:

```>.... [14:57:43 WARN]: [SCP] Task #199 for SCP v0.1 generated an exception
java.lang.IllegalArgumentException: Cannot spawn hanging entity for org.bukkit.entity.ItemFrame at Location{world=CraftWorld{name=main},x=-65.0,y=63.0,z=-48.0,pitch=0.0,yaw=0.0}
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.createEntity(CraftWorld.java:1912) ~[patched_1.15.2.jar:git-Paper-282]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1957) ~[patched_1.15.2.jar:git-Paper-282]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1543) ~[patched_1.15.2.jar:git-Paper-282]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawnEntity(CraftWorld.java:769) ~[patched_1.15.2.jar:git-Paper-282]
at net.scpuncontained.SCP.doors.NormalDoor$4.run(NormalDoor.java:190) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-282]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-282]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1253) ~[patched_1.15.2.jar:git-Paper-282]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-282]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1170) ~[patched_1.15.2.jar:git-Paper-282]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:959) ~[patched_1.15.2.jar:git-Paper-282]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]```

**Comment by Symphonic3** [comment]
This is still happening on Paper-284. Same stacktrace, Line 1912 of CraftWorld.

**Comment by Symphonic3** [comment]
This is still happening on the latest build of paper (354)
