### ISSUE TITLE
Playerheads are all shown as Steveheads

### ISSUE THREAD

**Issue by CloudeLecaw** [PaperMC/Paper#3672]
We tried the new Paper-12 today.

At the moment its not really useage for us.
Everything seems to look good, but playerheads used from the plugin everywhere are just shown as steve heads.

![Snag_2359696](https://user-images.githubusercontent.com/12080017/85956447-40138a00-b986-11ea-9355-5fd79c05f8ea.png)

This is how the GUI with look with Spigot
![Snag_237febd](https://user-images.githubusercontent.com/12080017/85956530-9ed90380-b986-11ea-9593-18892bc37ca8.png)

We hope this can be fixed with next build of papermc :)

**Comment by BomBardyGamer** [comment]
Are you able to provide any details about what you expected and some steps on how to reproduce this please?

**Comment by ConnorGillespie** [comment]
Not to sure if this helps, but this morning I tried to implement a SkullMeta into a custom recipe and it seemed to work just fine. About 15 minutes after implementing this change I recieved a NBT tag error, similar to this found on the papermc discord (https://gyazo.com/48c87ed02df0ff757136bfc6ea8ade6d). Like I said, I have no clue if this has anything to do with the issue but might as well throw it out there.

**Comment by hunterg2** [comment]
I'm having the same problem on my Paper server.

Lastnight, we updated from Paper 1.15.2 (Build #373) to Paper 1.16.1 (Build #1). Everything worked fine, except the plugin Head Database now fails to show the skins for all the heads when the are in an inventory. When placed as a block, the skin shows fine though.

**Comment by itsconnorgillespie** [comment]
Not to sure if this helps, but this morning I tried to implement a SkullMeta into a custom recipe and it seemed to work just fine. About 15 minutes after implementing this change I recieved a NBT tag error, similar to this found on the papermc discord (https://gyazo.com/48c87ed02df0ff757136bfc6ea8ade6d). Like I said, I have no clue if this has anything to do with the issue but might as well throw it out there.

**Comment by detoxv** [comment]
I had the exact error as above. My server uses skinned player heads as currency so i cannot update to 1.16.1 right now and having too many of any head it seems "bans" you effectively until the playerdata is wiped with the exact error as seen above. If i use creative to create 64 heads a few seconds later it effectively bans due to byte size exceeding allowed. 

On top of this all heads again are just steve heads at least old heads i have on the server from 1.15.2 and i couldn't find a way to /give a skull anymore using any website.

**Comment by CloudeLecaw** [comment]
fixed with latest build 14

**Comment by LoneDev6** [comment]
@CloudeLecaw this should also be reported to Spigot if it's a Spigot bug

**Comment by CloudeLecaw** [comment]
@LoneDev This bug just wasa appearing to papermc before build14 not to spigot

We noticed it when Paper build12 was released and we changed from spigot to it.

in spigot all heads shown correct.

**Comment by Frilioth** [comment]
Was this corrected for everyone in build14 as I have build21 and I still have this issue

<img width="1931" alt="Screenshot 2020-06-29 15 27 54" src="https://user-images.githubusercontent.com/46084236/86018597-7b14cc80-ba1d-11ea-8a9e-9e8b545fa443.png">

As you can see from the hotbar the heads look different but when they are placed on a solid block they all look the same. This only happens when they're placed, they still work fine when you put them on an armour stand. Any ideas?

**Comment by toboshii** [comment]
> Was this corrected for everyone in build14 as I have build21 and I still have this issue
> 
> <img alt="Screenshot 2020-06-29 15 27 54" width="1931" src="https://user-images.githubusercontent.com/46084236/86018597-7b14cc80-ba1d-11ea-8a9e-9e8b545fa443.png">
> 
> As you can see from the hotbar the heads look different but when they are placed on a solid block they all look the same. This only happens when they're placed, they still work fine when you put them on an armour stand. Any ideas?

Were these heads already in your inventory when you updated?

**Comment by Frilioth** [comment]
No.  I got them into my inventory by ctrl/alt and middle clicking on them, I've also changed the skin on my own avatar and /killed me, got the new head in my inventory and placed it on a block and this too reverts back to my original head until I pick it up.

**Comment by aikar** [comment]
basically your triggering the client bug that the patch that caused this issues original issue caused.

what your seeing is vanilla minecraft behavior. Paper has a patch to fix that, but it appears not every skull had the UUID updated correctly and some are still in the string format which can be iffy.

I'm not super familiar with vanilla commands but can't /data dump the nbt of a head? can you dump 2 or more heads that should be different?

**Comment by aikar** [comment]
though please open a new issue on this and copy your post to it, as this is a different issue than this ticket was about.

**Comment by alexandrage** [comment]
I have a similar problem, PlayerProfile is removed when the head is displayed. Install via meta.setPlayerProfile (profile);

**Comment by zenthesize** [comment]
having this issues again.
![ooof](https://user-images.githubusercontent.com/84170626/126573157-18a22571-4860-45f1-b32e-b8ed06e3f037.PNG)

**Comment by electronicboy** [comment]
protocol hacks are unsupported, nor is bumping old tickets a good idea when they've already been marked as resolved, if you can reproduce without proto hacks on a supported version, open a new issue.

**Comment by Camotoy** [comment]
If you're using Geyser, this is in no way Paper's fault. Feel free to open an issue on Geyser's GitHub.

**Comment by CloudeLecaw** [comment]
We also dont allow Bedrock Edition users on the server because it cant connect to mojangs skinndatabase nor it cant Show modded heads and Show all a steave heads what is making the world look odd if your working with Dekoration heads.
