### ISSUE TITLE
Players not getting Voluntary Exile advancement after killing a raid captain

### ISSUE THREAD

**Issue by erasurvival** [PaperMC/Paper#3729]
### What behaviour is expected:
The player getting the Voluntary Exile advancement after killing a raid captain 

### What behaviour is observed:
Nothing happens after the player kills the raid captain. I have to manually give them the advancement through the usage of the /advancement command

### Steps/models to reproduce:
Have a player without the Voluntary Exile advancement kill a raid captain. Observe if they get the advancement or not.

### Plugin list:
ActionHealth*, ArmorStandTools, Autorank, BBeeChecker, BetterRTP, BuycraftX, Citizens, ClearLag, ColoredAnvils*, CommandHook, CommandSpy*, CoreProtect, DiscordSRV, EditableSign, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, GriefPrevention, Harbor, HolographicDisplays, ImageOnMap, LuckPerms, Marriage, Multiverse-Core, PayRespecc*, PluginLibrary, RankSync*, SilkSpawners, SkQuery, Skript, Statz, SuperbVote, TAB, Vault, Votifier, VoxelSniper, WorldEdit, WorldGuard

### Paper build number:
Paper version git-Paper-24 (MC:1.16.1)

**Comment by paul-maxime** [comment]
Confirmed on my server. All the other 74 advancements work but not this one.

**Comment by Machine-Maker** [comment]
Unable to reproduce. Just tried on a brand new new build 43 server, and was able to get the advancement after killing a captain.

**Comment by BillyGalbreath** [comment]
Sounds like possibly another #2810 of simply not fully understanding the mechanic

**Comment by paul-maxime** [comment]
How did you manage to get the advancement?

- Paper-43, new world, I teleported to the nearest pillager outpost and killed a captain with a banner: I got bad omen but no advancement.
- Vanilla-1.16.1, same thing, new world, teleport to the nearest pillager output, killed a captain: I got bad omen AND the advancement.

12 players on my server managed to get _Hero of the Village_ and none of them have _Voluntary Exile_, I don't even know how this would be possible without a bug.

**Comment by Machine-Maker** [comment]
Yeah, I tp'd to the nearest outpost, waited around for one to spawn, killing off the non-banner mobs. I was in creative and had strength 255, but that shouldn't matter. when I killed one with the banner, I got the Voluntary Exile advancement.

**Comment by paul-maxime** [comment]
Here's two videos where I can't manage to get the advancement:

https://files.abovetheflood.fr/voluntary-exile.mp4
https://files.abovetheflood.fr/voluntary-exile-creative.mp4

On the first video I tried using a sword in survival mode, on the second one I tried in creative mode with strength 255, just in case it changed anything.

Here's a video where I manage to get the advancement on the same world, same player, at the same location, using Spigot:

https://files.abovetheflood.fr/voluntary-exile-spigot.mp4

**Comment by erasurvival** [comment]
> Here's two videos where I can't manage to get the advancement:
> 
> https://files.abovetheflood.fr/voluntary-exile.mp4
> https://files.abovetheflood.fr/voluntary-exile-creative.mp4
> 
> On the first video I tried using a sword in survival mode, on the second one I tried in creative mode with strength 255, just in case it changed anything.
> 
> Here's a video where I manage to get the advancement on the same world, same player, at the same location, using Spigot:
> 
> https://files.abovetheflood.fr/voluntary-exile-spigot.mp4

Would you mind sharing your plugin list?

**Comment by paul-maxime** [comment]
I did these tests without any plugin.

**Comment by erasurvival** [comment]
Oh wow, I see. Thanks for letting me know!

**Comment by paul-maxime** [comment]
I tried many Paper 1.16.1 builds and the bug is present on all of them, all the way back to `paperclip-1.jar`.
I will check the 1.15.2 builds later but I'm pretty sure they are all fine.

I also checked the wiki and saw this:
> Though bearing similar names, Voluntary Exile advancement does not use `voluntary_exile` criterion trigger, unlike most other advancements.

(source: https://minecraft.gamepedia.com/Advancement)

I wonder if this could be related to this bug.

**Comment by erasurvival** [comment]
Back when my server was on 1.15.2, we had no issues with this advancement.

Hope this information helps!

**Comment by paul-maxime** [comment]
Update: I managed to find the problematic patch!

I checked Paper 1.15.2: build 215 works fine but build 216 has the problem.
Here is the commit: https://github.com/PaperMC/Paper/commit/a6ac47e502d4cadef0c2c289956971739076c49c

I tried to build the latest version of paper 1.16.1 after removing the patch `0469-Fix-numerous-item-duplication-issues-and-teleport-is.patch`: the advancement works!

**Comment by paul-maxime** [comment]
Another update.

The problem is caused by the following line:
```java
if (stack instanceof CraftItemStack) stack.setAmount(0); // Paper - destroy this item - if this ever leaks due to game bugs, ensure it doesn't dupe, but don't nuke bukkit stacks of manually added items
```
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0469-Fix-numerous-item-duplication-issues-and-teleport-is.patch#L100

Removing this line is enough to fix the bug.

**Comment by Proximyst** [comment]
This points towards there being some data on the original item which was *not* cloned to the new one; a proper patch would be to ensure *all* data on the new item.

**Comment by paul-maxime** [comment]
I'm not familiar enough with the code to write a proper patch, but for the time being I fixed it the following way:

```java
if (stack instanceof CraftItemStack && stack.getType() != Material.WHITE_BANNER) stack.setAmount(0);
```

It works since the Ominous Banner worn by the pillagers is a `WHITE_BANNER`.

**Comment by aikar** [comment]
root issue is that CriterionConditionItem is checking count, and now the counts been deduced before the advancement progress is checked. 

can just make it ignore 0 counts and treat as 1

**Comment by paul-maxime** [comment]
It looks like the commit 243d2313b93448d8e525ef3c2c2a9a098ce69e09 also breaks this advancement.
Removing the patch "Fix-numerous-item-duplication-issues" is no longer enough to fix this issue.

I don't know why, especially since it works perfectly fine on Spigot.

Meanwhile, here is how I fixed it, hopefully permanently this time:

```java
Advancement voluntaryExile = Bukkit.getAdvancement(NamespacedKey.minecraft("adventure/voluntary_exile"));

@EventHandler
public void onEntityDeathEvent(EntityDeathEvent event)  {
    if (event.getEntity().getType() == EntityType.PILLAGER) {
        for (ItemStack drop : event.getDrops()) {
            if (drop.getType() == Material.WHITE_BANNER) {
                Player killer = event.getEntity().getKiller();
                if (killer != null) {
                    AdvancementProgress progress = killer.getAdvancementProgress(voluntaryExile);
                    for (String criteria : progress.getRemainingCriteria()) {
                        progress.awardCriteria(criteria);
                    }
                }
            }
        }
    }
}
```

**Comment by paul-maxime** [comment]
This bug is still relevant.

**Comment by Techno3600** [comment]
Can we get an update on a fix soon?

**Comment by Kon-len** [comment]
This bug is still a thing, I killed 2 Raid leaders and still didn't get the achievement

**Comment by siulung201314** [comment]
My players in the server still cannot get the achievement too.

**Comment by Machine-Maker** [comment]
> root issue is that CriterionConditionItem is checking count, and now the counts been deduced before the advancement progress is checked.
> 
> can just make it ignore 0 counts and treat as 1

I'm not sure this works. Since it's a CraftItemStack backed by a NMS itemstack, setting the amount to 0, sets the nms itemstack to null. So In the CriterionConditionItem, it's checking an air itemstack.

**Comment by Machine-Maker** [comment]
@paul-maxime Does removing that line still work to get the advancement? I only can see that working **if** the gamerule `doMobLoot` is set to false. If its set to true, simply removing that line doesn't get me the advancement.

**Comment by paul-maxime** [comment]
@Machine-Maker No, it's not enough anymore, that's why I had to write a plugin to grant the advancement manually.

**Comment by Machine-Maker** [comment]
Yeah, I figured. Just wanted to make sure.

**Comment by paul-maxime** [comment]
Still happening in 1.17 using build 19.

**Comment by reediculous456** [comment]
Still happening in 1.17 using build 104

**Comment by Redageddon** [comment]
Can confirm that this still exists in 1.17.1

**Comment by NotAlexNoyle** [comment]
I am also having this issue on 1.17.1. Hero of the village is also not triggered sometimes.

UPDATE: Switching from Airplane to Pufferfish-Purpur resolved this for me. As soon as the player who didn't have the achievement logged in again, they got it. I don't know if this is because Purpur/Pufferfish patched this, or because Paper was incidentally updated and Paper fixed it at some point without referencing this issue. Either way, I can't reproduce this problem on my server anymore with the new .jar

**Comment by Machine-Maker** [comment]
I think Purpur did fix this, but not in the way I did. So this is still and issue for Paper

**Comment by Carbuino** [comment]
As far as I can tell the advancement checks for the #raiders tag and any entity wearing the ominous banner. During one of my raids I checked this and none of the raiders had that tag, so the game couldn't detect when you completed the advancement.

**Comment by Machine-Maker** [comment]
I’m not sure what you mean by check if it had the tag, that’s not how tags work. Regardless, the issue is known, and there is an open fix for it.
