### ISSUE TITLE
Very slow chunk loading, strange chunk loading behavior in general

### ISSUE THREAD

**Issue by Malfrador** [PaperMC/Paper#4679]
### What behaviour is expected:
Chunks loading at decent and especially consistent speed.

### What behaviour is observed:
As soon as our server reaches higher player numbers (10-15+), chunk loading starts to behave very strange. Sometimes  chunks do not seem to load completely. They appear to be loaded on the server, as the server checks for collision and events related to chunks are working fine (e.g. adding chunks to a faction). But they are not loaded on the client, and are invisible. When using creative mode, it is possible to move around in the unloaded chunk, just as it would be in a loaded chunk. This includes collision. However, in survival mode movement is very buggy and not possible. Opening the chat is also not possible until the chunk has appeared.
Compared to normal lag-related chunk loading issues, the player is not falling down or anything. To me, it looks like the server loads the chunk fine, but its somehow not sent to the client correctly.
The issue can be fixed by relogging or by waiting. It can take more than 30 seconds for the chunks to appear when waiting.

This all happens while TPS stay at a stable 19.00 or more. RAM of the server is also more than half empty most of the time. Current Disk read/write speeds are also comparatively low when the issue is happening.  sparks tickmonitor is not showing any ticks that take a lot longer than usual while this happens. 

The issue appears more often after teleports (similar to #4342) , but also randomly when just walking around in the world. It seems to happen in spikes, e.g. there is a period of 30 seconds where no chunks load at all and then suddenly all missing chunks load very fast at once. Most of the time, it affects entire columns of chunks. Sometimes, just individual chunk sections. 

Picture of missing chunks. Notice how the chunks on the layer below the player in other columns are also missing. Picture was taken at appox. y = 100, so thats not the void.
![2020-10-22_17 37 16](https://user-images.githubusercontent.com/6106558/96896928-62c63300-148e-11eb-9527-4b05e4bafb76.png)

### Steps/models to reproduce:
I would love to have tried to reproduce the issue without plugins, but as it only appears with more than 15 players and our server relies heavily on nearly all of those plugins, it was not possible.

1. Use a paper 1.16 build. The issue is happening since we updated from 1.13.2, so since the early paper 1.16 builds.
2. Have some players online. 10 to 15 seems to be the limit. 
3. Try teleporting to existing, unloaded chunks. 

However, you might be able to reproduce very similar behavior with just one player by setting max-chunk-sends-per-tick to a very low value. 

### Plugin list:
```
Plugins (58): ArmouryXS, AuctionHouse, BossShopPro, Brewery, BroadcastXS*, Cannons, ChestShop, Citizens, CombatLogX, CommandNPC*, CommandsXL*, CourierNew, Craftconomy3*, DREFilter, DREMobs, DRERecipe, DungeonsXL, dynmap*, EnchantShopDRE*, Essentials, EssentialsSpawn, FactionsXL, FXLDC, HolographicDisplays, Itemizer, ItemsXL, LibsDisguises, LogBlock, LuckPerms, LWC, Multiverse-Core*, MythicMobs, OpenInv, ProtocolLib, Quests, Referral, ReForgeDRE, RespawnProtectorXS*, RFChairs, Shopkeepers, Skellett, SkQuery, skRayFall, Skript, spark, StackMob, StructureBoxes, TicketsXS*, TimeFold*, Vault, ViewDistanceTweaks, Votifier, VotingPlugin, WallstreetXL*, WarnXS, WorldBorder, WorldEdit, WorldGuard
```
### Things I already tried:

- Removing ViewDistanceTweaks. No difference, maybe even worse.
- Checking all our own plugins (the ones with "XL"/"XS" or "DRE" in their name) for interaction with chunks. None of them does anything with chunk loading.
- Setting ``max-chunk-sends-per-tick:`` to a very high (200), a very low value (10) and to -1. No difference
- Changing ``region-file-cache-size:`` to different values. No changes.
- Disabling ``queue-light-updates:`` - no difference. 
- Deleting villager POIs from the world folder - no difference. 
- Disabling ``no-tick-view-distance`` - nope.
- Reducing the ``view-distance`` to 4 - nope.
- Trying to find the issue with timings and spark. Nothing shows up. Timings are included below. 

### Paper version:
```
[17:23:22] [main/INFO]: [CHAT] This server is running Paper version git-Paper-244 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
```

### Anything else:
Timings: https://timings.aikar.co/?id=99582ccc9f4547bbaa427459370d2d59 (the small spike in the end is caused by me reloading Citizens twice). Issue appears from 16:50 on. 
As the issue forces players to relog very often and all at once, this also degrades the TPS after some time.

**Comment by Malfrador** [comment]
After some testing, it seems like the issues do _not_ happen when using Tuinity. So whatever causes this, Tuinity already fixes it. Not sure which patch tho.

**Comment by rayanbzd** [comment]
I have the exactly same problem on my server. And I don't find any solutions...

I tried latests tuinity build too, but the problem is still there for me...
> After some testing, it seems like the issues do _not_ happen when using Tuinity. So whatever causes this, Tuinity already fixes it. Not sure which patch tho.

**Comment by Proximyst** [comment]
It is rather likely that your issue was fixed by this patch: https://github.com/Spottedleaf/Tuinity/blob/de1983b38e97f5b6c2933d895dfff9e473567bda/patches/server/0015-Execute-chunk-tasks-mid-tick.patch

**Comment by Brokkonaut** [comment]
~~I can confirm that fix works, I applied the mentioned Tuinity patch to my server and did not have chunk loading issues any more.~~
(see below)

**Comment by aikar** [comment]
that patch is not safe to apply to paper, the main benefit there is going to be ticking during the entity ticking stage, which we intentionally have to skip because that can cause server crashes.

We need one of leafs other fixes to handle entity list state changes mid ticking to safely tick during entity ticking too.

**Comment by Brokkonaut** [comment]
It is not fixed in Tuinity, I tried that server for some days now and had the same issue. The chunk the player teleports to takes several seconds to load while the chunks around him are already loaded.

But Tuinity does not take as long as paper to load the chunk - with paper under high load (around 10tps) my players sometimes had to wait more than a minute until the chunk is loaded, in Tuinity it usually take less than 10 seconds.

**Comment by Malfrador** [comment]
> It is not fixed in Tuinity, I tried that server for some days now and had the same issue. The chunk the player teleports to takes several seconds to load while the chunks around him are already loaded.

Is only the teleporting issue not fixed or do chunks also fail to load randomly while flying/walking around in the world?
The teleport issue is still happening for me with Tuinity, but chunks load just fine (and fast) when walking around all the time. This is not the case with Paper

**Comment by Brokkonaut** [comment]
It is similar to paper but the load delay is not that extreme (5-10 secs instead of 30 secs or more)

**Comment by e-im** [comment]
Generally no longer relevant for 1.18.2. Tuinity has been merged into paper since 1.17.1. If you are still experiencing this issue/have more to add, please leave a comment.

**Comment by realguystuff** [comment]
I am also experiencing this problem in paper-1.19.

**Comment by Malfrador** [comment]
> I am also experiencing this problem in paper-1.19.

This exact issue was fixed with the Tuinity merge. Slow chunk loading on modern versions is usually due to rate-limiting, check the ``chunk-loading`` settings in your Paper config for that.

If you need further help, please join the PaperMC [discord ](https://discord.gg/papermc) (or use IRC or the forums) instead of bumping this nearly two year old issue. Replying to Github issues by default sends out email notifications to everyone who participated.
