### ISSUE TITLE
Item drop Mythicmobs Mobs not combined item paper 1.16.4

### ISSUE THREAD

**Issue by Chillchillnetwork** [PaperMC/Paper#4888]
### What behaviour is expected:
- Item drop mythicmobs combine item paper

### What behaviour is observed:
- Item drop Mythicmobs not combined item paper 1.16.4 By the way, making it combined is restart server , Enter the server again , load chunk but the name of the item is the same.

### Steps/models to reproduce:

Boss drop in mythicmobs
https://mcpaste.io/866a167ca699e822

- Example Mythicmobs NBT items not combined : https://www.youtube.com/watch?v=OMhOFHD6wyw

### Plugin list:
- AuctionHouse , BetterDrops , ChestShop , Citizens , Clearlag , CMI , Command Panels , EntityTrackerFixer , ItemEdit , Jobs , LockettePro , LuckPerms , MobFarmManager , MythicMobs-4.11.0 , PlaceholderAPI , ProtocolLib , Shopkeepers-2.12.0

### Paper version:
- paper-1.16.4-324 [Lastest Version Paper] Confirm!

**Comment by electronicboy** [comment]
We'd need to see the NBT data from those items as they're likely not the same, this is likely down to the spigot issue with modern servers where the data does not always match up properly due to technical reasons

**Comment by Machine-Maker** [comment]
#4886?

**Comment by Chillchillnetwork** [comment]
@Machine-Maker Yes I confirm paper 1.16.4 dev 324

**Comment by Chillchillnetwork** [comment]
I tried updating paper and it was the same.

**Comment by aikar** [comment]
Should be same issue I just fixed here: https://github.com/starlis/empirecraft/commit/1476d693a04b125ff1c7a068cbe3d8c2a5e47646

I will try to get this into Paper here soon, but gonna see if i can improve it to just change equals on the component modifiers checks instead, though I think legacy is still safer as it can deal with dummy blank wrapper components too.

**Comment by Charoxy** [comment]
I wait this

**Comment by hkkongou** [comment]
actually there are many people waiting for this paper update...
hopefully this issue can be fixed and closed asap

**Comment by electronicboy** [comment]
Spigot may have actually done some changes which negates the need for that change, we'll see, I guess

**Comment by tytyrocks12** [comment]
This issue still persists with mythicmobs. Has been causing tons of extra moderation to keep the trades going with the players, as 50% of all items do not match anymore.

**Comment by tytyrocks12** [comment]
I tested this on the latest version of Paper, Paper-406

**Comment by hkkongou** [comment]
did paper fixed this problem in latest patch?

**Comment by badnameok** [comment]
![image](https://user-images.githubusercontent.com/78036759/106279857-aee3f900-626f-11eb-9431-f45cd81befac.png)
just tested on 1.16.5, it doesn't seem to be fixed yet. NBT tags shown in picture. 1st Item: Directly dropped 2nd Item: After relogging.

**Comment by hkkongou** [comment]
Oh my god
This is a very big problem
How come there is no update for so long time and so less people notice this problem

**Comment by hkkongou** [comment]
> Should be same issue I just fixed here: [starlis/empirecraft@1476d69](https://github.com/starlis/empirecraft/commit/1476d693a04b125ff1c7a068cbe3d8c2a5e47646)
> 
> I will try to get this into Paper here soon, but gonna see if i can improve it to just change equals on the component modifiers checks instead, though I think legacy is still safer as it can deal with dummy blank wrapper components too.

@aikar  is already a month, how is it 
I am crying

**Comment by aurorasmiles** [comment]
Don't spam and randomly tag people.

**Comment by electronicboy** [comment]
Because to fix a problem, we need to be able to reproduce it and look deeper into it, given that this also highly falls into craftbukkits flawed handling of components, stuff like this is generally a pain in the ass to resolve without breaking other things

We don't support premium/closed source plugins, especially as they make it much harder to even bother to begin, and I have personally asked on multiple occasions for people to provide a minimal reproduction case.

If somebody wants to produce a jar with aikars fix, that might be worth testing, I'd build it myself but am not feeling well right now

**Comment by hkkongou** [comment]
This may not be a mythicmobs bug, some of the comment already said that spigot fixed this problem already ,🤔
I apologize for the tag and being annoying, but this problem is worth to discuss as mythicmobs and paper are popular

**Comment by badnameok** [comment]
here is a config and steps for reproduction. just in case it helps

1) put this into a .yml file in /MythicMobs/Items

```
material_common_zombie_flesh:
  Id: ROTTEN_FLESH
  Display: "&cZombie Flesh"
  Lore:
  - "&7Common Material"
```
  
2) restart server or /mm r
3) /mm i get material_common_zombie_flesh
4) disconnect and reconnect to the server
5) repeat step 3. The two items shouldn't stack and will have the same NBT as shown above.

**Comment by electronicboy** [comment]
We already have spigots fixes, if something else is interfering, we'd need more info on reproducing as this specifically looks like an issue with spigots chat API mangling stuff

reproduction in MM is generally useless given the whole premium/locked down nature of the plugin, it's not viable for us to go deep into debugging it

**Comment by aikar** [comment]
There is a possibility it's paper specific to making the issue worse, as we have some changes to the format that spigot doesn't that's at play here causing the issue. 

But i believe spigot had issues for any old item pre 1.16 comparing to 1.16 too. It's overall a mess...

**Comment by Hei5633** [comment]
Then is it going to be fix? Or Its staying this way forever?

**Comment by Proximyst** [comment]
If someone has any actual information to add, please do ping us on Discord or IRC.
The issue will be solved eventually. Asking over and over will not magically resolve it.

**Comment by electronicboy** [comment]
https://paste.gg/p/anonymous/76e0ff5952bd4c35a64c35230097cccd

Looks like the typical joyous conversions that CB does where they're wrapped, did spigot change this or something? I recall this being a constant issue after a vanilla update where vanilla changed the way components worked and basically broke all hell loose

**Comment by electronicboy** [comment]
https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0522-Update-itemstack-legacy-name-and-lore.patch
The itemstacks that MM is creating *are* in fact invalid, however, this only seems to be caught later on, looks like this needs applying to bukkit stacks too; Need to work out if this is an API issue or a plugin issue

**Comment by Machine-Maker** [comment]
losing as wontfix as it's getting less and less feasible to inject logic to fix this into the codecs required. The proper fix is for people not to use legacy color codes, and use proper components.
