### ISSUE TITLE
Grass block causing high server load [Chunk related?]

### ISSUE THREAD

**Issue by SecretlyJealous** [PaperMC/Paper#54]
My server has been having very strange tps problems with the new 1.9 update.
Here's what my warmroast is showing with 450 players online on my creative server: http://i.imgur.com/ca0EbHR.png
http://i.imgur.com/T6gkdu9.png
For some reason the chunk resources also seem high even after the recent patch but that may just be me (I'm not sure if it's normal?) I never had this issue with 1.8 leading me to think it's a 1.9 issue possibly related to chunks? My plots are each 516x516 and the top layer is made out of grass blocks so I suspect that there is some relation between the chunks and grass block timings because grass blocks have no reason to cause such bad timings.
The warmroast information was taken when I was using CraftBukkit version git-Spigot-b39373b-60f01ef (MC: 1.9) but paperspigot was giving more or less the same timings.
Also, I set my view distance as 2 in properties and it doesn't even seem like it's 2, here's a picture:
1.9 (View distance 2) http://i.imgur.com/cfiTtOg.jpg (Note, I could go beyond the fog and it still had chunks loaded)
1.8.8 (View distance 2) http://i.imgur.com/I7hztH1.jpg (This is much more efficient because when you move the previous chunk is no longer visible)

**Comment by Puremin0rez** [comment]
It should be noted that the 1.9 client currently has a bug where all chunks you load don't get unloaded until they go past your client set view distance - you can confirm this by setting your view distance really low then walking off into the distance, you'll notice you can still see pretty far back where you came from. This very well could be a feature aswell to combat servers lower view distances. This occurs on vanilla too.

Overall though 1.9 client is handling chunks very strange.

I do think 1.9 has some major chunk issues though, just pointing out that the visual stuff might be the clients fault.

**Comment by SecretlyJealous** [comment]
Has the issue also been reported? Also what's the best way to deal with this? I can barely run my server with the horrible tps.

**Comment by Puremin0rez** [comment]
The visual issue has been reported on the mojang bug tracker.

As for the TPS problems, I'm experiencing much of the same. Everyone is trying their best to figure out why this is such a problem in 1.9.

**Comment by zachbr** [comment]
Is this issue still relevant? Getting better, getting worse? Please test on latest and let us know.

**Comment by NachtRaben** [comment]
I'll add that the chunks not unloading, even if plugin induced unloaded, is still a valid problem up until the latest and I believe the issue is further upstream. Its one of the main reasons some larger networks hadn't updated to 1.9 yet.

**Comment by SecretlyJealous** [comment]
Running git-Paper-474
Here's what I got with 130 players online: http://paste.enginehub.org/nWbSu.profile
Here's what I got with 210 players online: http://paste.enginehub.org/sRcS8.profile
Here's what I got with 335 players online: http://paste.enginehub.org/58cS7.profile
Here's what I got with 350 players online: http://paste.enginehub.org/kMGS0.profile
Note, although the server load isn't 100% or anything Grass Block is still very high which is very strange considering it's a normal building block. I've had to limit my server capacity from 500 to 350 because of this issue though, I used to be able to hold 500 on 80% load with 1.8

**Comment by zachbr** [comment]
@NachtRaben 

> I'll add that the chunks not unloading, even if plugin induced unloaded, is still a valid problem up until the latest and I believe the issue is further upstream. Its one of the main reasons some larger networks hadn't updated to 1.9 yet.

Please verify this programmatically with a plugin such as WorldGuard or EssentialsX (does EssX have that feature?). There is currently a bug with the 1.9 client and what it sees as loaded is not indicative of what the server actually has loaded. The current issue for this #53 has supposedly been fixed at some point

**Comment by zachbr** [comment]
@SecretlyJealous Can we get an update on this with the latest build? I don't necessarily expect this to be perfect but I'd like to see if there is any improvement.

**Comment by SecretlyJealous** [comment]
@Zbob750 Here's what I got with 350/350: http://paste.enginehub.org/8uSyd.profile seems like it has improved slightly but still doesn't look like I'll be able to hold 500 players. I'll change the limit of my server to 400 though since server load isn't as high as before. Really hoping this issue gets sorted eventually.

**Comment by SecretlyJealous** [comment]
@Zbob750 Here's what I've got with 400/400: http://paste.enginehub.org/UNyyi.profile can't hold more then 400 since the load is very high.

**Comment by zachbr** [comment]
Thank you for the updates on this issue

**Comment by zachbr** [comment]
Everyone afflicted with this issue, please update to Build 621 or above and let us know how those run. Please and thank you.

**Comment by andris155** [comment]
view-distance integer (3-15) 2 not work.(?)
![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/14212471/45373a68-f833-11e5-906e-e979cc4196a6.PNG)

**Comment by SecretlyJealous** [comment]
@Zbob750 Taken with 350 players: http://paste.enginehub.org/2tSyM.profile 
Grass block load is still high at 10%.

**Comment by zachbr** [comment]
I believe this was fixed along with the other issues, either upstream or by us. It's been a long time since this ticket was opened.

On latest, this should be better. Reply again here if you think it needs more attention.
