### ISSUE TITLE
Some vanilla commands prevent mcfunctions from being loaded

### ISSUE THREAD

**Issue by Varauk** [PaperMC/Paper#6496]
### Expected behavior

Commands like `msg Notch hi` don't prevent a mcfunction from loading.

### Observed/Actual behavior

Adding `msg Notch hi` to a .mcfunction file results in an exception:

[12:24:21 ERROR]: Failed to load function minecraft:errortest/errortest
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: Not supported yet.
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.UnsupportedOperationException: Not supported yet.
        at net.minecraft.commands.ICommandListener$1.getBukkitSender(ICommandListener.java:30) ~[patched_1.17.1.jar:git-Paper-218]
        at net.minecraft.commands.CommandListenerWrapper.getBukkitSender(CommandListenerWrapper.java:322) ~[patched_1.17.1.jar:git-Paper-218]
        at net.minecraft.commands.CommandDispatcher.lambda$new$0(CommandDispatcher.java:210) ~[patched_1.17.1.jar:git-Paper-218]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:78) ~[patched_1.17.1.jar:git-Paper-218]
        at com.mojang.brigadier.CommandDispatcher.parseNodes(CommandDispatcher.java:358) ~[patched_1.17.1.jar:git-Paper-218]
        at com.mojang.brigadier.CommandDispatcher.parse(CommandDispatcher.java:348) ~[patched_1.17.1.jar:git-Paper-218]
        at net.minecraft.commands.CustomFunction.a(CustomFunction.java:61) ~[patched_1.17.1.jar:git-Paper-218]
        at net.minecraft.server.CustomFunctionManager.lambda$reload$3(CustomFunctionManager.java:86) ~[patched_1.17.1.jar:git-Paper-218]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
        ... 3 more

Namespacing doesn't work (since functions don't support plugin commands in the first place), and not all vanilla commands are affected (for example `gamemode creative Notch` works fine).

### Steps/models to reproduce

Add a new datapack to a world, create a test.mcfunction file, and add `msg Notch hi` to it. You can also use the datapack provided here and simply add it to the world/datapacks folder. Start the server.

[errortest.zip](https://github.com/PaperMC/Paper/files/7056161/errortest.zip)

### Plugin list

None

### Paper version

> version
[12:24:30 INFO]: Checking version, please wait...
[12:24:31 INFO]: This server is running Paper version git-Paper-218 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: e763a3d)
You are running the latest version
Previous version: git-Paper-216 (MC: 1.17.1)

This has been happening since version 216, so [this commit](https://github.com/PaperMC/Paper/commit/3773df24ce81173242bff99a2a9991f7a88a66b2) is most likely the cause.

### Agreements

- [X] I am running the latest version of Paper available from https://papermc.io/downloads.
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by Paper.

**Comment by Machine-Maker** [comment]
I believe this is fixed by an open PR. #6480 to be exact. It skips the permission check (which uses getBukkitSender) if the command source is CommansSource.NULL

**Comment by Varauk** [comment]
I checked, and yes it does fix this issue (the exception doesn't occur on startup, but then again the commit causing it was not yet added to that branch). I'll close this issue for now and see if that PR fixes it when it goes live. Thanks for the answer :)

**Comment by Machine-Maker** [comment]
It’s still a current issue, no need to close it. :)

**Comment by Varauk** [comment]
I saw that you updated your branch to the latest paper version and tried again: apparently it does not fix this issue, it's still the same stacktrace
> version
[11:02:06 INFO]: This server is running Paper version git-Paper-"711e62c" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 711e62c on feature/custom-commands-in-functions)

**Comment by Machine-Maker** [comment]
@Varauk did you ensure the new paper.yml setting I added is set to true? `settings.load-startup-plugin-commands` in paper.yml. You'd need to enable that for anything to change I think.

**Comment by Varauk** [comment]
To be honest I didn't see the new config (because I wasn't expecting one to be needed to fix a vanilla exception), but setting it to true sadly didn't help anyway. It's still the same stacktrace.

**Comment by sgenou** [comment]
I have the problem too and it is blocking me from using my homemade datapack.

**Comment by Machine-Maker** [comment]
@Varauk yep, the issue is different, am working on a fix right now. I thought the issue was smth else that my PR did fix, but it wasn't
